apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack-email
    receivers:
      - uid: slack-receiver
        type: slack
        settings:
          url: ${GRAFANA_SLACK_WEBHOOK_URL}
          title: |
            {{ template "default.title" . }}
          text: |
            {{ template "default.message" . }}
        disableResolveMessage: false
      - uid: email-receiver
        type: email
        settings:
          addresses: ${GRAFANA_ALERT_EMAIL}
          singleEmail: true
        disableResolveMessage: false
